// This file is auto-generated by packages/design-kit/tools/generate-icon-name.mjs.
// Do not edit manually.

export type IconName =
  | 'add'
  | 'arrow_back_ios_new'
  | 'arrow_top_left'
  | 'chat'
  | 'check'
  | 'check_circle'
  | 'chevron_right'
  | 'close'
  | 'code_blocks'
  | 'delete'
  | 'edit'
  | 'emergency_home'
  | 'help'
  | 'home'
  | 'info'
  | 'keyboard_arrow_down'
  | 'language'
  | 'menu'
  | 'notifications'
  | 'person'
  | 'print'
  | 'remove'
  | 'search'
  | 'settings'
  | 'warning';
